### ISSUE TITLE
Allow using as a library

### ISSUE THREAD

**Issue by diegobfernandez** [i9or/migralite#3]
hey! thanks for the great project.

would be nice if it allowed using it as a lib to make migrations part of the server setup, or applying migrations to in-memory databases during tests.

looking at the code I think there is just a small amount of change necessary for that.
- split files into LIB and CLI. mostly necessary because of [this import](https://github.com/i9or/migralite/blob/3f31ce02c279dc8131190739e1654fc0d1168959/index.ts#L9) and the [hashbang](https://github.com/i9or/migralite/blob/3f31ce02c279dc8131190739e1654fc0d1168959/index.ts#L1)
- Change [`applyMigration`](https://github.com/i9or/migralite/blob/3f31ce02c279dc8131190739e1654fc0d1168959/index.ts#L153) (LIB) so that it receives a `Database` object instead of a filename.
- Update `migrate` (CLI) to call `applyMigrations` passing a `Database` instance. e.g.: `await applyMigrations(connectToDatabase(database), migrations);`

if you'd like I can open a PR for it.

cheers.

**Comment by i9or** [comment]
Hi, thanks for the suggestion! It all makes sense. Let me finish with unit tests (#2, was procrastinating on it for a while, but now has extra motivation 😅) and then I'll add requested functionality myself. Shouldn't take long.

**Comment by diegobfernandez** [comment]
Thanks @i9or. In the meantime I've copied the project locally with enough changes for my tests to use an in-memory database.

**Comment by i9or** [comment]
Implemented in #5.

Hey @diegobfernandez, I have published a version with the split (v1.1.0). Feel free to reopen this issue if implementation is lacking anything you suggested.

**Comment by diegobfernandez** [comment]
Works perfectly! Drop-in replacement with the modified version I had.
Thanks again @i9or
